# Generated by Django 5.0.3 on 2024-05-09 05:37

from django.db import migrations, models
from django.db.utils import OperationalError

def create_lists_list_table(apps, schema_editor):
    # 检查表是否已存在
    table_name = "lists_list"
    try:
        if table_name not in schema_editor.connection.introspection.table_names():
            schema_editor.create_model(apps.get_model("lists", "List"))
    except OperationalError:
        # 如果表已经存在，则忽略创建操作
        pass

class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0002_item_text"),
    ]

    operations = [
        migrations.RunPython(create_lists_list_table)
    ]
